#include "Bridge.h"
#include "PortManager.h"
#include "mainwindow.h"
#include "./ui_mainwindow.h"
#include <QPushButton>
#include <QHBoxLayout>
#include <QWidget>
#include <QWebEngineView>
#include <QWebEnginePage>
#include <QKeyEvent>
#include <QWebChannel>

#include <QWebEngineProfile>
#include <QStandardPaths>
#include <QDir>
#include <QTimer>

#include <QFileInfo>
#include <QUrl>
#include <QFile>
#include <QTextStream>


MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    portManager = new PortManager(this);

    // Create right-side buttons
    QWidget *rightWidget = new QWidget(this);
    QHBoxLayout *buttonLayout = new QHBoxLayout(rightWidget);
    buttonLayout->setContentsMargins(0, 0, 0, 0);
    buttonLayout->setSpacing(5);

    QPushButton *btn1 = new QPushButton("Nest.in", rightWidget);
    QPushButton *btn2 = new QPushButton("Timeline Panel", rightWidget);
    QPushButton *btn3 = new QPushButton("Manual Panel", rightWidget);


    buttonLayout->addWidget(btn1);
    buttonLayout->addWidget(btn2);
    buttonLayout->addWidget(btn3);

    menuBar()->setCornerWidget(rightWidget, Qt::TopRightCorner);

    // Add WebEngineView to mainFrame
    webView = new QWebEngineView(ui->mainFrame);

    // Create or get the default profile
    QWebEngineProfile *profile = new QWebEngineProfile("lisyqProfile", this);

    QString storagePath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/webengine";
    QDir().mkpath(storagePath);
    profile->setPersistentStoragePath(storagePath);
    profile->setPersistentCookiesPolicy(QWebEngineProfile::ForcePersistentCookies);

    // Optional: also use this profile for the WebView
    webView->setPage(new QWebEnginePage(profile, webView));

    // Adds the Bridge ===========
    Bridge *bridge = new Bridge(this);

    QWebChannel *channel = new QWebChannel(this);
    channel->registerObject("NativeObject", bridge);
    // Adding the Bridge End ====


    QVBoxLayout *frameLayout = new QVBoxLayout(ui->mainFrame);
    frameLayout->setContentsMargins(0, 0, 0, 0);
    frameLayout->addWidget(webView);

    QString path = QCoreApplication::applicationDirPath() + "/main.html";
    webView->load(QUrl::fromLocalFile(path));


    connect(webView, &QWebEngineView::loadFinished, this,
            [this](bool ok)
            {
                if (!ok) return;

                injectWebChannelScript();

                // Slight delay to ensure script loads
                QTimer::singleShot(10, this, [this]() {
                    initializeWebChannel();
                });
            });

    webView->page()->setWebChannel(channel);

    devTools = new QWebEngineView(); // still no parent
    devTools->setPage(new QWebEnginePage(profile, devTools));

    // Attach DevTools to the main webView
    webView->page()->setDevToolsPage(devTools->page());
    devTools->resize(800, 600);

    SavePath = "";
    FromOpenFile = false;
    asNew = true;


    // ==================
    //  Context Menus
    // ==================

    contextMenu_Sub = new QMenu(this);

    QAction *consub_edit = contextMenu_Sub->addAction("Edit");
    QAction *consub_remove = contextMenu_Sub->addAction("Remove");
    QAction *consub_copy = contextMenu_Sub->addAction("Copy");
    QAction *consub_trackoption = contextMenu_Sub->addAction("Track Options");
    QAction *consub_addtotemplate = contextMenu_Sub->addAction("Add to Templates");

    connect(consub_edit, &QAction::triggered, this, &MainWindow::onContextEdit);
    connect(consub_remove, &QAction::triggered, this, &MainWindow::onContextRemove);
    connect(consub_copy, &QAction::triggered, this, &MainWindow::onContextCopy);
    connect(consub_trackoption, &QAction::triggered, this, &MainWindow::onContextTrackOptions);
    connect(consub_addtotemplate, &QAction::triggered, this, &MainWindow::onContextAddToTemplate);
}



MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::keyPressEvent(QKeyEvent *event)
{
    if(event->key() == Qt::Key_F12)
    {
        if(devTools->isVisible())
            devTools->hide();
        else
            devTools->show();
    }
    QMainWindow::keyPressEvent(event); // pass to default
}


//On window Resize
void MainWindow::resizeEvent(QResizeEvent *event){
    QMainWindow::resizeEvent(event);  // call base implementation
     webView->page()->runJavaScript("gen_ruler();");
}



 // ==========================
 // Bridge inject       ======
 // ==========================
void MainWindow::injectWebChannelScript()
{
    QString js = R"(
        (function() {
            if (typeof QWebChannel === 'undefined') {
                var script = document.createElement('script');
                script.setAttribute("comment", "Auto Generated By QT Bridge");
                script.src = 'qrc:///qtwebchannel/qwebchannel.js';
                script.type = 'text/javascript';
                document.head.appendChild(script);
            }
        })();
    )";

    webView->page()->runJavaScript(js);
}


// This Mimics the Webview2 Host Object
void MainWindow::initializeWebChannel()
{
    QString js = R"(
        (function() {

            if (typeof QWebChannel === 'undefined') {
                var script = document.createElement('script');
                script.src = 'qrc:///qtwebchannel/qwebchannel.js';
                script.onload = setupChannel;
                document.head.appendChild(script);
            } else {
                setupChannel();
            }

            function setupChannel() {
                new QWebChannel(qt.webChannelTransport, function(channel) {

                    // Ensure structure exists
                    window.chrome = window.chrome || {};
                    window.chrome.webview = window.chrome.webview || {};
                    window.chrome.webview.hostObjects = window.chrome.webview.hostObjects || {};

                    // Assign NativeObject exactly like WebView2
                    window.chrome.webview.hostObjects.NativeObject =
                        channel.objects.NativeObject;
                });
            }

        })();
        console.log("Native Bridge Injected to runtime");
    )";

    webView->page()->runJavaScript(js);
}


// ==========================
// Bridge inject End    =====
// ==========================



void MainWindow::on_actionOpen_triggered(){
    openLSYSFile();
}


void MainWindow::on_actionSave_triggered(){
    webView->page()->runJavaScript("save_to_file();");
}

void MainWindow::on_actionPort_Configuration_triggered(){
    webView->page()->runJavaScript("openPortConfig();");
}

void MainWindow::on_actionDMX_Config_Patcher_triggered(){
    webView->page()->runJavaScript("openDMXConfig();");
}

void MainWindow::onReady(){
    //---
}



 // Saving Files goes here ===========

void Bridge::put_data(const QString &data){
    if(mainWindow) {
        mainWindow->data_string = data;

    }
}



void Bridge::Save_To_File()
{
    if (mainWindow) {
        mainWindow->Save_File();
    }
}


bool Bridge::AsNewTrigger(){
    if(mainWindow) {
        if(mainWindow->FromOpenFile == true){
              return false;
        }

        mainWindow->asNew = true;
        mainWindow->SavePath = "";

        return true;
    }

    return false;

}


void MainWindow::Save_File()
{
    if (SavePath.isEmpty() || asNew)
    {
        QString defaultFileName = QDir::homePath() + "/LSYS file.lsys";

        QString fileName = QFileDialog::getSaveFileName(
            this,
            "Save File",
            defaultFileName,
            "LSYS Files (*.lsys)"
            );

        if (!fileName.isEmpty())
        {
            // Ensure the file has .lsys extension
            if (!fileName.endsWith(".lsys", Qt::CaseInsensitive))
                fileName += ".lsys";

            QFile file(fileName);
            if (file.open(QIODevice::WriteOnly | QIODevice::Text))
            {
                QTextStream out(&file);
                out << data_string;
                file.close();

                SavePath = fileName;
                asNew = false;

                qDebug() << "Saved to:" << SavePath;
            }
        }
        else
        {
            if (SavePath.isEmpty())
                asNew = true;
        }
    }
    else
    {
        QFile file(SavePath);
        if (file.open(QIODevice::WriteOnly | QIODevice::Text))
        {
            QTextStream out(&file);
            out << data_string;
            file.close();

            qDebug() << "Saving File:" << SavePath;
        }
    }

    FromOpenFile = false;
}

// Saving Files end        ===========







// Opens a Native File Picker for .lsys files
void MainWindow::openLSYSFile()
{
    QString fileName = QFileDialog::getOpenFileName(
        this,
        "Open LSYS File",
        QDir::homePath(),
        "LSYS Files (*.lsys)"
        );

    if (fileName.isEmpty())
        return;

    QFile file(fileName);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;

    QTextStream in(&file);
    QString fileContent = in.readAll();
    file.close();

    // Escape single quotes for JS
    fileContent.replace("'", "\\'");

    webView->page()->runJavaScript(
        "load_from_file('" + fileContent + "');"
        );

    SavePath = fileName;
    FromOpenFile = false;
    asNew = false;
}


bool Bridge::Open_FileDirectory()
{
    if (!mainWindow) return false;

    mainWindow->Open_FileDirectory_Native();
    return true;
}

//Opens a Media file picker, which can provide native link info
void MainWindow::Open_FileDirectory_Native()
{
    QString filePath = QFileDialog::getOpenFileName(
        this,
        "Select A Media File",
        "",
        ""
        );

    if (!filePath.isEmpty())
    {
        // Escape path for JS
        QString escapedPath = QUrl::fromLocalFile(filePath).toString();

        // Call JS function
        webView->page()->runJavaScript(
            QString("setMediaPath('%1');").arg(escapedPath)
            );

        // To-DO: Optional toast notification

    }
}

// ================================
// PORT Channel Management
// ================================



void MainWindow::addComPort(int index, const QString &portname)
{
    portManager->addSerialPort(index, portname);
}

void MainWindow::removeComPort(int index)
{
    portManager->removeSerialPort(index, true);
}

void MainWindow::addUdpChannel(int index, const QString &address, int port)
{
    portManager->addUdpChannel(index, address, port);
}

void MainWindow::removeUdpChannel(int index)
{
    portManager->removeUdpChannel(index);
}

QString MainWindow::getSystemComPortsJson()
{
    return portManager->getSystemPortsJson();
}

QString MainWindow::getManagedPortsJson()
{
    return portManager->getManagedPortsJson();
}

QString MainWindow::getUdpListJson()
{
    return portManager->getUdpListJson();
}


void MainWindow::setDf(const QString &data)
{
    if (portManager)
        portManager->setDf(data);
}


void MainWindow::outputs_v2()
{
    if (portManager)
        portManager->outputs_v2();
}





bool Bridge::add_comport(int index, const QString &portname)
{
    if (!mainWindow) return false;
    mainWindow->addComPort(index, portname);
    return true;
}

bool Bridge::add_udpchannel(int index, const QString &address, int port)
{
    if (!mainWindow) return false;
    mainWindow->addUdpChannel(index, address, port);
    return true;
}

QString Bridge::get_udplist_json()
{
    if (!mainWindow) return "{}";
    return mainWindow->getUdpListJson();
}

void Bridge::disconnect_udp(int index)
{
    if (!mainWindow) return;
    mainWindow->removeUdpChannel(index);
}

QString Bridge::get_comlist()
{
    if (!mainWindow) return "{}";
    return mainWindow->getSystemComPortsJson();
}

QString Bridge::get_comports()
{
    if (!mainWindow) return "{}";
    return mainWindow->getManagedPortsJson();
}

void Bridge::disconnect_com(int index)
{
    if (!mainWindow) return;
    mainWindow->removeComPort(index);
}


//Getting the Data
void Bridge::set_values(int port, const QString &data)
{
    Q_UNUSED(port); // placeholder like VB

    if (!mainWindow)
        return;

    mainWindow->setDf(data);
}

void Bridge::outputs(){
    mainWindow->outputs_v2();
}






//Context Menus
void MainWindow::showContentSubMenu(){
    QPoint globalPos = QCursor::pos();   // show at mouse position
    contextMenu_Sub->exec(globalPos);
}


void Bridge::Show_content_menu(){
    mainWindow->showContentSubMenu();
}


void MainWindow::onContextEdit()
{
    webView->page()->runJavaScript("open_edit_for(timeline_data[selected_track_index].sub_tracks[selected_content.getAttribute('content_id')], 'edit')");
}

void MainWindow::onContextRemove()
{
    webView->page()->runJavaScript("remove_content()");
}

void MainWindow::onContextCopy()
{
    webView->page()->runJavaScript("copy_content();");
}

void MainWindow::onContextTrackOptions()
{
    //Open the Track Option Context Menu
}

void MainWindow::onContextAddToTemplate()
{
    webView->page()->runJavaScript("sendToTimelineTemplates();");
}


