#include "Bridge.h"
#include "mainwindow.h"
#include "./ui_mainwindow.h"
#include <QPushButton>
#include <QHBoxLayout>
#include <QWidget>
#include <QWebEngineView>
#include <QWebEnginePage>
#include <QKeyEvent>
#include <QWebChannel>

#include <QWebEngineProfile>
#include <QStandardPaths>
#include <QDir>
#include <QTimer>

#include <QFile>
#include <QTextStream>


MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    // Create right-side buttons
    QWidget *rightWidget = new QWidget(this);
    QHBoxLayout *buttonLayout = new QHBoxLayout(rightWidget);
    buttonLayout->setContentsMargins(0, 0, 0, 0);
    buttonLayout->setSpacing(5);

    QPushButton *btn1 = new QPushButton("Nest.in", rightWidget);
    QPushButton *btn2 = new QPushButton("Timeline Panel", rightWidget);
    QPushButton *btn3 = new QPushButton("Manual Panel", rightWidget);


    buttonLayout->addWidget(btn1);
    buttonLayout->addWidget(btn2);
    buttonLayout->addWidget(btn3);

    menuBar()->setCornerWidget(rightWidget, Qt::TopRightCorner);

    // Add WebEngineView to mainFrame
    webView = new QWebEngineView(ui->mainFrame);

    // Create or get the default profile
    QWebEngineProfile *profile = new QWebEngineProfile("lisyqProfile", this);

    QString storagePath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/webengine";
    QDir().mkpath(storagePath);
    profile->setPersistentStoragePath(storagePath);
    profile->setPersistentCookiesPolicy(QWebEngineProfile::ForcePersistentCookies);

    // Optional: also use this profile for the WebView
    webView->setPage(new QWebEnginePage(profile, webView));

    // Adds the Bridge ===========
    Bridge *bridge = new Bridge(this);

    QWebChannel *channel = new QWebChannel(this);
    channel->registerObject("NativeObject", bridge);
    // Adding the Bridge End ====


    QVBoxLayout *frameLayout = new QVBoxLayout(ui->mainFrame);
    frameLayout->setContentsMargins(0, 0, 0, 0);
    frameLayout->addWidget(webView);

    QString path = QCoreApplication::applicationDirPath() + "/main.html";
    webView->load(QUrl::fromLocalFile(path));


    connect(webView, &QWebEngineView::loadFinished, this,
            [this](bool ok)
            {
                if (!ok) return;

                injectWebChannelScript();

                // Slight delay to ensure script loads
                QTimer::singleShot(10, this, [this]() {
                    initializeWebChannel();
                });
            });

    webView->page()->setWebChannel(channel);

    devTools = new QWebEngineView(); // still no parent
    devTools->setPage(new QWebEnginePage(profile, devTools));

    // Attach DevTools to the main webView
    webView->page()->setDevToolsPage(devTools->page());
    devTools->resize(800, 600);

    SavePath = "";
    FromOpenFile = false;
    asNew = true;


}



MainWindow::~MainWindow()
{
    delete ui;
}

void MainWindow::keyPressEvent(QKeyEvent *event)
{
    if(event->key() == Qt::Key_F12)
    {
        if(devTools->isVisible())
            devTools->hide();
        else
            devTools->show();
    }
    QMainWindow::keyPressEvent(event); // pass to default
}
 // ==========================
 // Bridge inject       ======
 // ==========================
void MainWindow::injectWebChannelScript()
{
    QString js = R"(
        (function() {
            if (typeof QWebChannel === 'undefined') {
                var script = document.createElement('script');
                script.setAttribute("comment", "Auto Generated By QT Bridge");
                script.src = 'qrc:///qtwebchannel/qwebchannel.js';
                script.type = 'text/javascript';
                document.head.appendChild(script);
            }
        })();
    )";

    webView->page()->runJavaScript(js);
}


// This Mimics the Webview2 Host Object
void MainWindow::initializeWebChannel()
{
    QString js = R"(
        (function() {

            if (typeof QWebChannel === 'undefined') {
                var script = document.createElement('script');
                script.src = 'qrc:///qtwebchannel/qwebchannel.js';
                script.onload = setupChannel;
                document.head.appendChild(script);
            } else {
                setupChannel();
            }

            function setupChannel() {
                new QWebChannel(qt.webChannelTransport, function(channel) {

                    // Ensure structure exists
                    window.chrome = window.chrome || {};
                    window.chrome.webview = window.chrome.webview || {};
                    window.chrome.webview.hostObjects = window.chrome.webview.hostObjects || {};

                    // Assign NativeObject exactly like WebView2
                    window.chrome.webview.hostObjects.NativeObject =
                        channel.objects.NativeObject;
                });
            }

        })();
        console.log("Native Bridge Injected to runtime");
    )";

    webView->page()->runJavaScript(js);
}


// ==========================
// Bridge inject End    =====
// ==========================



void MainWindow::on_actionOpen_triggered(){
    openLSYSFile();
}


void MainWindow::on_actionSave_triggered(){
    webView->page()->runJavaScript("save_to_file();");
}

void MainWindow::onReady(){
    //---
}



 // Saving Files goes here ===========

void Bridge::put_data(const QString &data){
    if(mainWindow) {
        mainWindow->data_string = data;
        qDebug() << "Received from JS:" << mainWindow->data_string;
    }
}



void Bridge::Save_To_File()
{
    if (mainWindow) {
        mainWindow->Save_File();
    }
}


bool Bridge::AsNewTrigger(){
    if(mainWindow) {
        if(mainWindow->FromOpenFile == true){
              return false;
        }

        mainWindow->asNew = true;
        mainWindow->SavePath = "";

        return true;
    }


}


void MainWindow::Save_File()
{
    if (SavePath.isEmpty() || asNew)
    {
        QString defaultFileName = QDir::homePath() + "/LSYS file.lsys";

        QString fileName = QFileDialog::getSaveFileName(
            this,
            "Save File",
            defaultFileName,
            "LSYS Files (*.lsys)"
            );

        if (!fileName.isEmpty())
        {
            // Ensure the file has .lsys extension
            if (!fileName.endsWith(".lsys", Qt::CaseInsensitive))
                fileName += ".lsys";

            QFile file(fileName);
            if (file.open(QIODevice::WriteOnly | QIODevice::Text))
            {
                QTextStream out(&file);
                out << data_string;
                file.close();

                SavePath = fileName;
                asNew = false;

                qDebug() << "Saved to:" << SavePath;
            }
        }
        else
        {
            if (SavePath.isEmpty())
                asNew = true;
        }
    }
    else
    {
        QFile file(SavePath);
        if (file.open(QIODevice::WriteOnly | QIODevice::Text))
        {
            QTextStream out(&file);
            out << data_string;
            file.close();

            qDebug() << "Saving File:" << SavePath;
        }
    }

    FromOpenFile = false;
}

// Saving Files end        ===========







// Opens a Native File Picker for .lsys files
void MainWindow::openLSYSFile()
{
    QString fileName = QFileDialog::getOpenFileName(
        this,
        "Open LSYS File",
        QDir::homePath(),
        "LSYS Files (*.lsys)"
        );

    if (fileName.isEmpty())
        return;

    QFile file(fileName);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;

    QTextStream in(&file);
    QString fileContent = in.readAll();
    file.close();

    // Escape single quotes for JS
    fileContent.replace("'", "\\'");

    webView->page()->runJavaScript(
        "load_from_file('" + fileContent + "');"
        );

    SavePath = fileName;
    FromOpenFile = false;
    asNew = false;
}
