#include "Bridge_Nest.h"
#include "PortManager.h"
#include "nestwindow.h"
#include "./ui_nestwindow.h"
#include <QPushButton>
#include <QHBoxLayout>
#include <QWidget>
#include <QWebEngineView>
#include <QWebEnginePage>
#include <QKeyEvent>
#include <QWebChannel>

#include <QWebEngineProfile>
#include <QStandardPaths>
#include <QDir>
#include <QTimer>

#include <QFileInfo>
#include <QUrl>
#include <QFile>
#include <QTextStream>
#include <QMessageBox>

NestWindow::NestWindow(QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::NestWindow)
{
    ui->setupUi(this);

    portManager = new PortManager(this);

    // Create right-side buttons
    QWidget *rightWidget = new QWidget(this);
    QHBoxLayout *buttonLayout = new QHBoxLayout(rightWidget);
    buttonLayout->setContentsMargins(0, 0, 0, 0);
    buttonLayout->setSpacing(5);


    //Top Buttons
    btnTimeline = new QPushButton("Studio Panel", rightWidget);



    connect(btnTimeline, &QPushButton::clicked, this, &NestWindow::onTimelineClicked);


    buttonLayout->addWidget(btnTimeline);


    menuBar()->setCornerWidget(rightWidget, Qt::TopRightCorner);

    // Add WebEngineView to mainFrame
    webView = new QWebEngineView(ui->mainFrame);

    // Create or get the default profile
    QWebEngineProfile *profile = new QWebEngineProfile("lisyqProfile", this);

    QString storagePath = QStandardPaths::writableLocation(QStandardPaths::AppDataLocation) + "/webengine";
    QDir().mkpath(storagePath);
    profile->setPersistentStoragePath(storagePath);
    profile->setPersistentCookiesPolicy(QWebEngineProfile::ForcePersistentCookies);

    // Optional: also use this profile for the WebView
    webView->setPage(new QWebEnginePage(profile, webView));

    // Adds the Bridge ===========
    Bridge_Nest *bridge = new Bridge_Nest(this);

    QWebChannel *channel = new QWebChannel(this);
    channel->registerObject("NativeObject", bridge);
    // Adding the Bridge End ====


    QVBoxLayout *frameLayout = new QVBoxLayout(ui->mainFrame);
    frameLayout->setContentsMargins(0, 0, 0, 0);
    frameLayout->addWidget(webView);

    QString path = QCoreApplication::applicationDirPath() + "/views/nest_main.html";
    webView->load(QUrl::fromLocalFile(path));


    connect(webView, &QWebEngineView::loadFinished, this,
            [this](bool ok)
            {
                if (!ok) return;

                injectWebChannelScript();

                // Slight delay to ensure script loads
                QTimer::singleShot(10, this, [this]() {
                    initializeWebChannel();
                });
            });

    webView->page()->setWebChannel(channel);

    devTools = new QWebEngineView(); // still no parent
    devTools->setPage(new QWebEnginePage(profile, devTools));

    // Attach DevTools to the main webView
    webView->page()->setDevToolsPage(devTools->page());
    devTools->resize(800, 600);

    SavePath = "";
    FromOpenFile = false;
    asNew = true;


    // ==================
    //  Context Menus
    // ==================



}



NestWindow::~NestWindow()
{
    delete ui;
}

void NestWindow::keyPressEvent(QKeyEvent *event)
{
    if(event->key() == Qt::Key_F12)
    {
        if(devTools->isVisible())
            devTools->hide();
        else
            devTools->show();
    }
    QMainWindow::keyPressEvent(event); // pass to default
}


//On window Resize
void NestWindow::resizeEvent(QResizeEvent *event){
    QMainWindow::resizeEvent(event);  // call base implementation
     webView->page()->runJavaScript("gen_ruler();");
}



 // ==========================
 // Bridge inject       ======
 // ==========================
void NestWindow::injectWebChannelScript()
{
    QString js = R"(
        (function() {
            if (typeof QWebChannel === 'undefined') {
                var script = document.createElement('script');
                script.setAttribute("comment", "Auto Generated By QT Bridge");
                script.src = 'qrc:///qtwebchannel/qwebchannel.js';
                script.type = 'text/javascript';
                document.head.appendChild(script);
            }
        })();
    )";

    webView->page()->runJavaScript(js);
}


// This Mimics the Webview2 Host Object
void NestWindow::initializeWebChannel()
{
    QString js = R"(
        (function() {

            if (typeof QWebChannel === 'undefined') {
                var script = document.createElement('script');
                script.src = 'qrc:///qtwebchannel/qwebchannel.js';
                script.onload = setupChannel;
                document.head.appendChild(script);
            } else {
                setupChannel();
            }

            function setupChannel() {
                new QWebChannel(qt.webChannelTransport, function(channel) {

                    // Ensure structure exists
                    window.chrome = window.chrome || {};
                    window.chrome.webview = window.chrome.webview || {};
                    window.chrome.webview.hostObjects = window.chrome.webview.hostObjects || {};

                    // Assign NativeObject exactly like WebView2
                    window.chrome.webview.hostObjects.NativeObject =
                        channel.objects.NativeObject;
                });
            }

        })();
        console.log("Native Bridge Injected to runtime");
    )";

    webView->page()->runJavaScript(js);
}


// ==========================
// Bridge inject End    =====
// ==========================


void NestWindow::setActiveButton(QPushButton *active)
{
    QString activeStyle =
        "background-color: gray;"
        "color: white;";

    QString normalStyle = "";

    btnTimeline->setStyleSheet(normalStyle);
    // btnManual->setStyleSheet(normalStyle);

    active->setStyleSheet(activeStyle);
}


void NestWindow::onTimelineClicked()
{
    setActiveButton(btnTimeline);
    webView->page()->runJavaScript("modeSelect('timeline');");
}





// Tool Strips and Others



void NestWindow::on_actionPort_Configuration_triggered(){
    webView->page()->runJavaScript("openPortConfig('port_configurator.html');");
}


void NestWindow::onReady(){
    //---
}

\



 // Saving Files goes here ===========



// Saving Files end        ===========





// ================================
// PORT Channel Management
// ================================



void NestWindow::addComPort(int index, const QString &portname)
{
    portManager->addSerialPort(index, portname);
}

void NestWindow::removeComPort(int index)
{
    portManager->removeSerialPort(index, true);
}

void NestWindow::addUdpChannel(int index, const QString &address, int port)
{
    portManager->addUdpChannel(index, address, port);
}

void NestWindow::removeUdpChannel(int index)
{
    portManager->removeUdpChannel(index);
}

QString NestWindow::getSystemComPortsJson()
{
    return portManager->getSystemPortsJson();
}

QString NestWindow::getManagedPortsJson()
{
    return portManager->getManagedPortsJson();
}

QString NestWindow::getUdpListJson()
{
    return portManager->getUdpListJson();
}


void NestWindow::setDf(const QString &data)
{
    if (portManager)
        portManager->setDf(data);
}


void NestWindow::outputs_v2()
{
    if (portManager)
        portManager->outputs_v2();
}





bool Bridge_Nest::add_comport(int index, const QString &portname)
{
    if (!nestWindow) return false;
    nestWindow->addComPort(index, portname);
    return true;
}

bool Bridge_Nest::add_udpchannel(int index, const QString &address, int port)
{
    if (!nestWindow) return false;
    nestWindow->addUdpChannel(index, address, port);
    return true;
}

QString Bridge_Nest::get_udplist_json()
{
    if (!nestWindow) return "{}";
    return nestWindow->getUdpListJson();
}

void Bridge_Nest::disconnect_udp(int index)
{
    if (!nestWindow) return;
    nestWindow->removeUdpChannel(index);
}

QString Bridge_Nest::get_comlist()
{
    if (!nestWindow) return "{}";
    return nestWindow->getSystemComPortsJson();
}

QString Bridge_Nest::get_comports()
{
    if (!nestWindow) return "{}";
    return nestWindow->getManagedPortsJson();
}

void Bridge_Nest::disconnect_com(int index)
{
    if (!nestWindow) return;
    nestWindow->removeComPort(index);
}


//Getting the Data
void Bridge_Nest::set_values(int port, const QString &data)
{
    Q_UNUSED(port); // placeholder like VB

    if (!nestWindow)
        return;

    nestWindow->setDf(data);
}

void Bridge_Nest::outputs(){
    nestWindow->outputs_v2();
}






//Context Menus



